### ISSUE TITLE
HUD build fails

### ISSUE THREAD

**Issue by M1cha** [chenxiaolong/Unity-for-Arch#186]
```
[ 47%] Generating libhud/libhud.signals
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
CMake Error at /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:112 (elseif):
  given arguments:

    "VERSION_LESS" "3.1"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:501 (_pkgconfig_parse_options)
  /home/m1cha/Unity-for-Arch/hud/src/hud-14.10+14.10.20140924/cmake/GtkDocScanGObjWrapper.cmake:5 (pkg_check_modules)


docs/libhud/CMakeFiles/libhud-gtxdoc-fixxref.dir/build.make:122: recipe for target 'docs/libhud/libhud/libhud.signals' failed
make[2]: *** [docs/libhud/libhud/libhud.signals] Error 1
CMakeFiles/Makefile2:1937: recipe for target 'docs/libhud/CMakeFiles/libhud-gtxdoc-fixxref.dir/all' failed
make[1]: *** [docs/libhud/CMakeFiles/libhud-gtxdoc-fixxref.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by bebehei** [comment]
Same here, have you found a solution?

**Comment by M1cha** [comment]
unfortunately not. I gave up on Arch and will wait for Papyros to be released :P

**Comment by PeterCxy** [comment]
In fact, I haven't ever succeeded in building this project when I was using ArchLinux.

**Comment by bebehei** [comment]
Ok, the solution is: cmake is too new in ArchLinux. Ubuntu 14.04 uses cmake 2.8.2 (Archlinux uses 3.1), so I grabbed the cmake PKGBUILD, replaced the version with 2.8.2 and built it.

Of course I had to write a pacman-wrapper, too:
```
#!/bin/bash

echo "executing pacman $*"

# repo-make fails if the package-list is not updated manually
/usr/bin/pacman -Sy
# keep own version of cmake
/usr/bin/pacman $(echo $* | sed 's/cmake//')
```

**Comment by bebehei** [comment]
Ok, actually, I would recommend using cmake version 2.8.11. The unity package only builds with cmake 2.8.11.

Off topic: I successfully built the whole unity shell. It looks great on Arch. During the next week, I'll push the changes into my git-repository and create PRs.

**Comment by chenxiaolong** [comment]
Fixed (well, worked around) in the testing branch with commit e74b68e57ac2284261b8e36dda652d87d8a57274.

Note that the developer gtk-doc documentation is no longer built.
