### ISSUE TITLE
If pyalpm is not installed, a nice error-message shows up.

### ISSUE THREAD

**Issue by bebehei** [chenxiaolong/Unity-for-Arch#189]
Fresh and clean chroot, I had not the pyalpm-package installed: This was the error-message:

    [user@host Unity-for-Arch]# ./build-and-install.sh 
    ./build-and-install.sh: line 70: cd: Please: No such file or directory
    ==> ERROR: PKGBUILD does not exist.
    ./build-and-install.sh: line 70: cd: install: No such file or directory
    ==> ERROR: PKGBUILD does not exist.
    ./build-and-install.sh: line 70: cd: the: No such file or directory
    ==> ERROR: PKGBUILD does not exist.
    ./build-and-install.sh: line 70: cd: pyalpm: No such file or directory
    ==> ERROR: PKGBUILD does not exist.
    ./build-and-install.sh: line 70: cd: package: No such file or directory
    ==> ERROR: PKGBUILD does not exist.

The presentation of the error-message is quite artistic.

**Comment by chenxiaolong** [comment]
Thanks! Fixed in the testing branch as commit `e11af7b8a3135cd84bba960782a259fd88ae8e7c`

**Comment by bebehei** [comment]
Thanks, the presentation of the error-message is still awesome!
