### ISSUE TITLE
repo-make.conf broken

### ISSUE THREAD

**Issue by bebehei** [chenxiaolong/Unity-for-Arch#191]
is repo-make.conf still supported? I had to make huge changes to make it work.

If so, are you willing to accept a PR?

**Comment by chenxiaolong** [comment]
I personally don't use repo-make.conf (it was contributed to the repo by someone else). If you have it fixed, I'd be happy to merge a PR.

**Comment by bebehei** [comment]
Ok, I'll do. This is just mainly de-parsing your markdown and putting it into repo-make.conf
