### ISSUE TITLE
missing pygtk dependency for ccsm

### ISSUE THREAD

**Issue by blaale** [chenxiaolong/Unity-for-Arch#192]
Running the compiz configuration manager (ccsm in commandline) requires pygtk to be installed, currently it is not brought in as a dependency.

**Comment by bebehei** [comment]
Yep, this is true. I've verified it. It would be great, If you open a mergeable PR. @chenxiaolong can merge it much easier.

**Comment by chenxiaolong** [comment]
Thanks! Merged into the `testing` branch as commit c6956809c06c11603bd837dcc791a6766e2194ad (will be merged into master soon).
