### ISSUE TITLE
Nautilus icon duplication in unity launcher

### ISSUE THREAD

**Issue by blaale** [chenxiaolong/Unity-for-Arch#196]
In the unity panel the nautilus icon appears to be relatively non-functional, when pressing it instead of opening a nautilus window tied to the icon you have just clicked a duplicate icon is creating in the runing applications section. It's a little hard to explain so see the attached screenshots for details.
![Duplicate menu (topmost is default icon)](https://cloud.githubusercontent.com/assets/8383085/6722754/b4146ac0-ce2a-11e4-8800-faa9d8ecbd20.png)
![default icon shows file op progress, created one does not](https://cloud.githubusercontent.com/assets/8383085/6722755/b52d0ed0-ce2a-11e4-857a-1afa0d247de5.jpg)

Curiously the 'dummy' icon does display file opperations progress, whilst the actual functional one does not. Locking the second icon and removing the original 'solves' the issue with the exception of file operations not being displayed.

After locking both icons I had a look at com.canonical.Unity.Launcher and the contents are as follows (with a few redactions):

['application://nautilus.desktop', *SNIP* ,'application://org.gnome.Nautilus.desktop', *SNIP*]

Removing org.gnome.Nautilus.desktop from /usr/share/applications and /home/$USER/.local/share/applications and closing all existing nautilus windows from the launcher resolves the issue. From what I can tell the issue is primarily related to the existence of that said desktop file. I haven't investigated the root cause although removing these files does work.

Could this be fixed in the repo's PKGBUILD? I could perhaps submit a pull request? The changes to it would be minor although. So far I haven't noticed any side effects but I didn't really bother digging into the unity and nautilus sources to see what effects it might have.

EDIT: Haven't confirmed if it is a direct side effect but after deleting org.gnome.Nautilus.desktop I was unable to open USB storage devices via the launcher (inside nautilus and from desktop worked fine). Running xdg-mime default nautilus.desktop inode/directory solved this.

**Comment by bebehei** [comment]
> Removing org.gnome.Nautilus.desktop from /usr/share/applications and /home/$USER/.local/share/applications and closing all existing nautilus windows from the launcher resolves the issue.

You had simply two desktop-files describing the same thing. Unity does not know how to handle this. The real solution is removing `~/.local/share/applications/org.gnome.Nautilus.desktop` and nothing more. Deleting the desktop-file from `/usr/share/applications` is wrong.

**Comment by chenxiaolong** [comment]
This should hopefully be fixed in the latest round of updates. If not, please reopen this bug.
