### ISSUE TITLE
unity-control-center and upower-compat are in conflict

### ISSUE THREAD

**Issue by doolz** [chenxiaolong/Unity-for-Arch#202]
Updated /etc/pacman.conf with the following,

    [Unity-for-Arch]
    SigLevel = Optional TrustAll
    Server = http://dl.dropbox.com/u/486665/Repos/$repo/$arch

    [Unity-for-Arch-Extra]
    SigLevel = Optional TrustAll
    Server = http://dl.dropbox.com/u/486665/Repos/$repo/$arch

Ran pacman -Syu and updated the new Arch Repos successfully.

After running pacman -S $(pacman -Slq Unity-for-Arch) I get the following output,

    looking for conflicting packages...
    error: unresolvable package conflicts detected
    error: failed to prepare transaction (conflicting dependencies)
    :: unity-control-center and upower-compat are in conflict

Typing the following command seems to be a work around,

    pacman -S --ignore upower-compat $(pacman -Slq Unity-for-Arch)

**Comment by chenxiaolong** [comment]
Should be fixed with the GNOME 3.16 merge. `upower-compat` is no longer in the repo.
