### ISSUE TITLE
Gnome 3.16

### ISSUE THREAD

**Issue by Sureiya** [chenxiaolong/Unity-for-Arch#203]
I believe everything in the repo may be broken due to gnome 3.16. My system broke after updating this morning, and the only way I was able to recover was by building and installing packages in the 3.16 branch.

**Comment by chenxiaolong** [comment]
Thanks for letting me know! I've merged the `gnome-3.16` branch into `testing`. Once my server finishes building the packages, I'll merge into `master`.

**Comment by Sureiya** [comment]
Awesome, how stable is it?

I was able to get a somewhat working desktop, but a LOT of things were broken. I wasn't able to build a lot of the 3.16 branch pacakges though, I was getting errors from CMake.

**Comment by emhs** [comment]
This appears to be related to #205.

**Comment by chenxiaolong** [comment]
Everything should be ported and working now. Packages are now in `[Unity-for-Arch]`.
