### ISSUE TITLE
Video glitch on desktop with desktop icons

### ISSUE THREAD

**Issue by sollidsnake** [chenxiaolong/Unity-for-Arch#211]
I got this windows like glitch in the last update:

![snapshot1](https://cloud.githubusercontent.com/assets/1778350/7447098/6e61278a-f1c4-11e4-998c-97792ce0cb12.png)

I already tried 'compiz.reset' and reinstalling everything, but no use. If I disable the 'icons on desktop' option the glitch doesn't happen.

**Comment by chenxiaolong** [comment]
We have to wait until Ubuntu patches Nautilus 3.16 until this will be fixed. Ubuntu keeps forward-porting some old code to make nautilus draw the background image.

**Comment by MingcongBai** [comment]
It is quite irritating... given the dramatic change in Nautilus code it's merely impossible to forward port the code.

**Comment by blaale** [comment]
I have the same issue, you can 'fix' it by downgrading to nautilus-ubuntu 3.14. My very brief usage so far seems to indicate it behaves with the rest of the new gnome update but your mileage may vary so be careful.

Assuming you still have the tarball in /var/cache/pacman/pkg then run;
sudo pacman -U /var/cache/pacman/pkg/nautilus-ubuntu-3.14.2-3-x86_64.pkg.tar.xz

**Comment by chenxiaolong** [comment]
@blaale Thanks for letting us know the old version still works! If anyone cleared the pacman cache already, the old nautilus-ubuntu package is still available from my build server: https://jenkins.noobdev.io/job/ArchLinux_Build_Package/604/

**Comment by chenxiaolong** [comment]
Fixed in 02289917a7fd1545aa2f7fdb1d41976d1c7befcc which is now in `[Unity-for-Arch]`. Looks like Ubuntu's GNOME 3 team were quick to fix the issue in the gnome3-staging PPA.
