### ISSUE TITLE
Nothing works with Gnome 3.18

### ISSUE THREAD

**Issue by blydro2** [chenxiaolong/Unity-for-Arch#221]
I've compiled from source and installed packages from the repo, but nothing works, presumably because of Gnome 3.18. Unity won't start, and compiz throws a bunch of errors on startup. (compiz.reset). 

Does anybody know which packages need to be downgraded to get Unity to work?
Thanks

**Comment by sollidsnake** [comment]
I don't know all of them, but I'm sure you'll need to downgrade at least all gnome packages to 3.16. Or upgrade gtk2 and gtk3-ubuntu to 3.18. But probably there'll still be more packages.

**Comment by sollidsnake** [comment]
I was able to get unity running again after updating the some packages with xenial version and other changes. But there's still some issues. I'll try to fix them and push a new branch when I have the time.

**Comment by chenxiaolong** [comment]
All the packages have been updated to GNOME 3.20-compatible versions now. There are a few bugs here and there (especially with `ubuntu-themes`), but it should be usable now.
