### ISSUE TITLE
No indicators or application menu after update to 3.18

### ISSUE THREAD

**Issue by sollidsnake** [chenxiaolong/Unity-for-Arch#222]
I managed to update packages to xenial version, with a few tweaks, and got unity working again with a up-to-date arch. However there's a issue I couldn't fix yet. There's no indicator or application menu in the top panel, just the application name. Does anybody know what could be missing to fix this?
![spectacle o32038](https://cloud.githubusercontent.com/assets/1778350/12155185/ffbe2012-b4aa-11e5-9729-5f9d02ee1591.png)

**Comment by chenxiaolong** [comment]
This should be fixed in the latest Xenial/GNOME-3.20 updates.

![screenshot from 2016-05-14 22-07-49](https://cloud.githubusercontent.com/assets/646253/15271622/61aefb72-1a20-11e6-80b6-69a63500ea87.png)
