### ISSUE TITLE
Failed to start Update Bamf index for Unity shell.

### ISSUE THREAD

**Issue by matthew65536** [chenxiaolong/Unity-for-Arch#223]
I keep trying to log in with unity, but lightdm sends me back to the login screen, and when i check systemctl to make sure nothing is messed up i get bamfwatcher.service failed, when i do systemctl status bamfwatcher.service i get:

bamfwatcher.service - Update Bamf index for Unity shell
   Loaded: loaded (/usr/lib/systemd/system/bamfwatcher.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2016-02-12 23:23:12 CST; 1min 56s ago
  Process: 3170 ExecStart=/usr/bin/bamfwatcher (code=exited, status=127)
 Main PID: 3170 (code=exited, status=127)

Feb 12 23:23:12 Acer-peppy systemd[1]: bamfwatcher.service: Unit entered failed state.
Feb 12 23:23:12 Acer-peppy systemd[1]: bamfwatcher.service: Failed with result 'exit-code'.
Feb 12 23:23:12 Acer-peppy systemd[1]: bamfwatcher.service: Service hold-off time over, scheduling restart.
Feb 12 23:23:12 Acer-peppy systemd[1]: Stopped Update Bamf index for Unity shell.
Feb 12 23:23:12 Acer-peppy systemd[1]: bamfwatcher.service: Start request repeated too quickly.
Feb 12 23:23:12 Acer-peppy systemd[1]: Failed to start Update Bamf index for Unity shell.
Feb 12 23:23:12 Acer-peppy systemd[1]: bamfwatcher.service: Unit entered failed state.
Feb 12 23:23:12 Acer-peppy systemd[1]: bamfwatcher.service: Failed with result 'start-limit'.

Can you please tell me what i did wrong?

**Comment by ForumLiker** [comment]
I have the same problem

$ sudo systemctl srart bamfwatcher.service
$ Failed to start bamfwatcher.service: Unit bamfwatcher.service failed to load: No such file or directory.

**Comment by Toromino** [comment]
Had the same problem, can't log in due to this error, does anyone know how to fix this?

**Comment by chenxiaolong** [comment]
This is now fixed with the introduction of the pacman hook mechanism.
