### ISSUE TITLE
dee-ubuntu

### ISSUE THREAD

**Issue by horsemanoffaith** [chenxiaolong/Unity-for-Arch#229]
Building package fails with the following error:

../../src/dee-serializable-model.c: In function ‘dee_serializable_model_get_position’:
../../src/dee-serializable-model.c:1329:3: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
   while (!dee_model_is_last (self, iter) && iter != _iter)
   ^~~~~
../../src/dee-serializable-model.c:1331:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘while’
     pos++;
     ^~~

Patching this file with the following patch results in a successful build:

--- a/src/dee-serializable-model.c	2016-06-12 14:32:47.589079617 -0700
+++ b/src/dee-serializable-model.c	2016-06-12 14:34:53.629081073 -0700
@@ -1327,8 +1327,10 @@
   pos = 0;
   _iter = dee_model_get_first_iter (self);
   while (!dee_model_is_last (self, iter) && iter != _iter)
+    {
     _iter = dee_model_next (self, _iter);
     pos++;
+    }
 
   if (iter == _iter)
     return pos;

I'm no programmer, so I'm not sure if this is correct. Could you advise?

**Comment by horsemanoffaith** [comment]
I have found that there was a bug submitted to the https://launchpad.net/dee page. This package has a patch listed and the above patch is correct. For some reason the Ubuntu developers still have not changed the original file.

**Comment by smamontov** [comment]
Here is the mentioned bug: https://bugs.launchpad.net/dee/+bug/1579529
