### ISSUE TITLE
Failed to find target qtchooser

### ISSUE THREAD

**Issue by justrobd** [chenxiaolong/Unity-for-Arch#238]
$cd gsettings-qt
$makepkg -sci
==> Making package: gsettings-qt 0.1.16.04.20160329-1 (Tue Oct 11 03:15:50 CDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
error: target not found: qtchooser
==> ERROR: 'pacman' failed to install missing dependencies.

qtchooser is in the makedepends() I tried it without it and it seems to work ok. I think it should be removed as a dependency.

**Comment by horsemanoffaith** [comment]
I have done the same. Unity works correctly so far. I will update this and dee-qt on my github page in the next couple of days.

**Comment by justrobd** [comment]
This isn't related to the post title but, I want to let you know that some of the builds are failing because there are things like this "../" in the the prepare(). It doesn't need to cd to the patches the patches are in the same working directory as the PKGBUILD. I been taking care of mine but wanted let you know they exist and will cause the build to fail with this error.  For example with the hud: 
Extracting sources...
  -> Extracting hud_14.10+16.04.20160415.orig.tar.gz with bsdtar
==> Starting prepare()...
patch: **** Can't open patch file ../0001-Use-Python-2.patch : No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by horsemanoffaith** [comment]
Are you building this off Chen's github or mine? As far as I know, all my PKGBUILDS work correctly.

**Comment by justrobd** [comment]
I was building off of yours and then when I was trying to build the unity package I was getting an error as well. I am going to start from scratch. And I'll keep you informed if you don't mind?

**Comment by horsemanoffaith** [comment]
My bad... I have the wrong version of Unity on my Github page. Somehow I committed Unity 7.5, and the current working version is 7.4. If you use Chenxiaolong's Github and build Unity, it should work correctly. I have no problems with you keeping me informed. It helps me know that my commits are correct.

**Comment by horsemanoffaith** [comment]
I just updated my unity commit. It should build correctly now.

**Comment by chenxiaolong** [comment]
This is fixed by commit bc7450e4b3921d44eacf87c515d1d00ca0f40eb3
