### ISSUE TITLE
How to resolve nux and missing package glewmx

### ISSUE THREAD

**Issue by justrobd** [chenxiaolong/Unity-for-Arch#239]
checking for NUX_GRAPHICS... no
configure: error: Package requirements (glib-2.0 >= 2.25.14
                  gdk-pixbuf-2.0
                  cairo >= 1.9.14
                  libpng >= 1.2.44
                  gl glu glew glewmx xext x11
                  xxf86vm
                  sigc++-2.0
		              xinerama
                  ) were not met:

No package 'glewmx' found

EDIT this can be ignored: I figured it out.

**Comment by horsemanoffaith** [comment]
What did you do to fix the issue?
