### ISSUE TITLE
Can't build gtk3-ubuntu package

### ISSUE THREAD

**Issue by miguel-rn** [chenxiaolong/Unity-for-Arch#240]
When building gtk3-ubuntu, it tries to download gtk+3.0_3.20.6-2ubuntu~xenial2.Debian.tar.xz from ppa.launchpad.net but curl returns error #22 "The requested URL returned error 404". I assume the source URL needs to be updated.

**Comment by horsemanoffaith** [comment]
Please take a look at the closed issues- this question has already been asked and resolved.
