### ISSUE TITLE
nautilus-ubuntu 3.22.0.1+22+gd72934b crashes on startup

### ISSUE THREAD

**Issue by horsemanoffaith** [chenxiaolong/Unity-for-Arch#241]
THIS IS FROM THE UNITY-FOR-ARCH TESTING REPO

[mikearch@mikearchlaptop ~]$ nautilus

(nautilus:2112): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number

(nautilus:2112): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.

(nautilus:2112): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:841:10: not a number

(nautilus:2112): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:841:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(nautilus:2112): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1981:14: not a number

(nautilus:2112): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1981:14: Expected a string.

(nautilus:2112): Gtk-WARNING **: Theme parsing error: nautilus.css:55:71: Using one color stop with linear-gradient() is deprecated.

(nautilus:2112): Gtk-WARNING **: Theme parsing error: nautilus.css:56:71: Using one color stop with linear-gradient() is deprecated.

** (nautilus:2112): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-ld9rT4wGvw: Connection refused

(nautilus:2112): GLib-GObject-WARNING **: Two different plugins tried to register 'TerminalNautilus'.

(nautilus:2112): GLib-GObject-CRITICAL **: g_type_add_interface_dynamic: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(nautilus:2112): GLib-GObject-WARNING **: Two different plugins tried to register 'TerminalNautilusMenuItem'.

(nautilus:2112): GLib-GObject-WARNING **: Two different plugins tried to register 'NautilusNste'.

(nautilus:2112): GLib-GObject-CRITICAL **: g_type_add_interface_dynamic: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

** (nautilus:2112): WARNING **: Unable to get contents of the bookmarks file: Error opening file /home/mikearch/.gtk-bookmarks: No such file or directory

** (nautilus:2112): WARNING **: Unable to get contents of the bookmarks file: Error opening file /home/mikearch/.gtk-bookmarks: No such file or directory

(nautilus:2112): GLib-GObject-WARNING **: invalid cast from 'TerminalNautilus' to '<invalid>'

(nautilus:2112): GLib-GObject-WARNING **: invalid cast from 'NautilusNste' to '<invalid>'

(nautilus:2112): GLib-GObject-WARNING **: invalid cast from 'TerminalNautilus' to '<invalid>'

(nautilus:2112): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)
___________________________________________________________________________________________

Downgrading nautilus-ubuntu to 3.20.1+17+gf84d431 corrects the issue.

**Comment by chenxiaolong** [comment]
This is fixed by commit 2a43164da5c4516eeb8eb4fa21b8c9396f8e476e. Ubuntu's `multiarch_fallback.patch` patch was causing the Nautilus plugins to be loaded twice.

**Comment by horsemanoffaith** [comment]
Thank you Chen!!

**Comment by chenxiaolong** [comment]
No problem! By the way, the `master` branch should be fully working now (including Ubuntu's mixture of upstart/systemd user session mess).

**Comment by horsemanoffaith** [comment]
As far as I'm aware, there were only small issues that were causing problems-  I did my best to keep my Unity-for-Arch Github page up to date with those small issues so people could build Unity without doing it themselves. By the way, I sent you an e-mail about two weeks ago... did you get it?
