### ISSUE TITLE
libindicate: 2 compiling errors

### ISSUE THREAD

**Issue by at0mikk** [chenxiaolong/Unity-for-Arch#243]
./generated/ListenerServer.cs(62,10): error CS0670: Fields cannot have void type
./generated/ListenerServer.cs(62,28): error CS1547: Keyword 'void" can not be used in this context

**Comment by GoogleBot42** [comment]
I am having the same problem

**Comment by horsemanoffaith** [comment]
Same here.

**Comment by jmauss** [comment]
Same issue

**Comment by horsemanoffaith** [comment]
I found the issue. The current version of gtk-sharp-2 causes the build on libindicate to fail. Downgrading gtk-sharp-2 allows libindicate to build, but this is only a band-aid. Not sure how to fix the issue.

**Comment by horsemanoffaith** [comment]
The current version of gtk-sharp-2 is 2.12.42-1. I downgraded to 2.12.29-1 and was able to build successfully.

**Comment by chenxiaolong** [comment]
This is fixed now. I temporarily disabled building the mono bindings as I'm not familiar with it enough to fix the issue.
