### ISSUE TITLE
Cannot change themes

### ISSUE THREAD

**Issue by horsemanoffaith** [chenxiaolong/Unity-for-Arch#245]
I mentioned this in my previous issue- I cannot change themes in unity-control-center. I'm stuck with the ugly GNOME defaults. Any help would be greatly appreciated!

**Comment by Adikso** [comment]
I also have this problem.

**Comment by chenxiaolong** [comment]
I can't seem to reproduce this with the latest packages:

* unity-settings-daemon `15.04.1.16.10.20161003-2`
* unity-control-center `15.04.0.16.10.20161003.1-1`

I can successfully switch between Adwaita, Ambiance, and Radiance.

**Comment by horsemanoffaith** [comment]
I have done a full rebuild, updating packages as I went along as the sources allowed me to. I have a working system, themes included. I'm not quite sure what was causing the problem, but I did find several PKGBUILDs that I had to edit (not yours, chen- ones that I have on my fork from your repository). I'm glad that I've got unity all back up and working properly! Thanks for all your hard work!!!

**Comment by nicman23** [comment]
so closed?

**Comment by horsemanoffaith** [comment]
Don't know... I wasn't the only one having the issue. Adikso, is this still an issue for you?

**Comment by nicman23** [comment]
The compile is still running I ll edit this tomorrow

**Comment by Adikso** [comment]
@horsemanoffaith I decided not to use Unity anymore. Later it became completely broken and i haven't been able to log into it. Too much hassle, mess with packages and living with default GNOME theme was too tiring. I am using KDE Plasma now :)

**Comment by horsemanoffaith** [comment]
Thanks for the reply, Adikso... I'll close this issue.
