### ISSUE TITLE
error while compiling 'nautilus-ubuntu'

### ISSUE THREAD

**Issue by at0mikk** [chenxiaolong/Unity-for-Arch#247]
-> Downloading nautilus_3.22.1-1ubuntu0~yakkety1.debian.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging/+files/nautilus_3.22.1-1ubuntu0~yakkety1.debian.tar.xz
    Aborting...

**Comment by chenxiaolong** [comment]
@at0mikk This should be fixed in 4ce30d4753b40c54cdaf5eab6355c02c4a5ba981
